-- Create testimonials table
create table public.testimonials (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  name text not null,
  role text not null,
  company text not null,
  content text not null,
  image text,
  sort_order bigint default 0
);

-- Enable RLS
alter table public.testimonials enable row level security;

-- Create policies
create policy "Public read access"
  on public.testimonials for select
  using ( true );

create policy "Authenticated insert access"
  on public.testimonials for insert
  with check ( auth.role() = 'authenticated' );

create policy "Authenticated update access"
  on public.testimonials for update
  using ( auth.role() = 'authenticated' );

create policy "Authenticated delete access"
  on public.testimonials for delete
  using ( auth.role() = 'authenticated' );
